version: '3.8'

services:
  siaes-db:
    image: postgres:16-alpine
    container_name: siaes-postgres
    restart: always
    environment:
      POSTGRES_DB: siaes_db
      POSTGRES_USER: siaes_user
      POSTGRES_PASSWORD: siaes_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siaes_user -d siaes_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  siaes-api:
    build:
      context: .
      dockerfile: /src/SIAES.API/Dockerfile
    container_name: siaes-webapi
    restart: always
    ports:
    - "8082:8080"
    - "8083:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=siaes-db;Port=5432;Database=siaes_db;Username=siaes_user;Password=siaes_password
    depends_on:
      siaes-db:
        condition: service_healthy

  sonarqube:
    image: sonarqube:10.8.1-community
    container_name: siaes-sonarqube
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: